### ISSUE TITLE
Can't connect from another machine

### ISSUE THREAD

**Issue by roger-** [mickael-kerjean/webpty#3]
Is it possible to bind to 0.0.0.0 instead of 127.0.0.1?

**Comment by scriptzteam** [comment]
https://github.com/mickael-kerjean/webpty/blob/ed3a4dd0674fff98ab103ed275c0cb04ca1fd126/webfleet/model/server_state.go#L68

https://github.com/mickael-kerjean/webpty/blob/ed3a4dd0674fff98ab103ed275c0cb04ca1fd126/ctrl/middleware.go#L74

https://github.com/mickael-kerjean/webpty/blob/ed3a4dd0674fff98ab103ed275c0cb04ca1fd126/main.go#L62

https://github.com/mickael-kerjean/webpty/blob/ed3a4dd0674fff98ab103ed275c0cb04ca1fd126/common/ssl/root.go#L33

https://github.com/mickael-kerjean/webpty/blob/ed3a4dd0674fff98ab103ed275c0cb04ca1fd126/common/ssl/root.go#L38

**Comment by arminus** [comment]
Hardcoded to 127.0.0.1? Is the idea to have to run it behind a proxy?

**Comment by mickael-kerjean** [comment]
That is the default unless you use the fleet server, I'm not sure to follow what change do you suggest?

**Comment by arminus** [comment]
My first test was in my local lab where my assumption (based on 'It was made to "just work"') was that I could connect from a box within the same LAN right away. 

Maybe this is just a documentation improvement or misunderstanding on my part - but if I understand this correctly, I need the fleet server to connect to webpty **in any case** - because I don't see the point of running a browser on the box webpty is actually running on so that it can connect to 127.0.0.1...?

**Comment by mickael-kerjean** [comment]
Oopsy yes, I made a change on that part of the code base a few days ago on the fleet server and didn't realise it would cause issue without using the fleet server. I've revert it and it should work now

**Comment by roger-** [comment]
Thanks, works now!
